repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: pylint
	name: pylint
	entry: python -m pylint._main_
	language: system
	types: [python]
